# Generated by Django 3.0.3 on 2020-02-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='farmer_login',
            field=models.BooleanField(default=False, verbose_name="Farmer's Login Status"),
        ),
        migrations.AddField(
            model_name='farmer',
            name='farmer_social_auth_provider',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Farmer's Social Auth Provider"),
        ),
        migrations.AddField(
            model_name='farmer',
            name='farmer_token_social_auth',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Farmer's Token Social Auth"),
        ),
    ]
