# Generated by Django 3.0.3 on 2020-02-12 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0002_auto_20200211_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='farmer_social_auth_provider',
            field=models.CharField(choices=[('Google', 'google-oauth2'), ('Facebook', 'facebook'), ('Manual Registration', None)], default=None, max_length=50, null=True, verbose_name="Farmer's Social Auth Provider"),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farmer_user_auth',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_account', to=settings.AUTH_USER_MODEL, verbose_name="Famer's Authentication Account"),
        ),
    ]
