# Generated by Django 3.0.3 on 2020-02-12 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20200212_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='farmer_city',
            field=models.CharField(default=django.utils.timezone.now, help_text="Farmer's City", max_length=60, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='farmer_country',
            field=models.CharField(default=django.utils.timezone.now, help_text="Farmer's Counrty", max_length=50, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='farmer_landmark',
            field=models.CharField(blank=True, help_text="Farmer's Landmark", max_length=100, null=True, verbose_name='Landmark'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='farmer_place',
            field=models.CharField(default=django.utils.timezone.now, help_text="Farmer's Palces", max_length=70, verbose_name='Places'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='farmer_plot_no',
            field=models.CharField(blank=True, default='', help_text="Farmer's Plot No", max_length=50, verbose_name='Plot No'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='farmer_state',
            field=models.CharField(default='', help_text="Farmer's State", max_length=70, verbose_name='State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='farmer_street',
            field=models.CharField(default='', help_text="Farmer's Street", max_length=150, verbose_name='Steet'),
            preserve_default=False,
        ),
    ]
