# Generated by Django 3.0.3 on 2020-02-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_auto_20200212_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='farmer_login',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='farmer_social_auth_provider',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='farmer_token_social_auth',
        ),
    ]
