# Generated by Django 3.0.3 on 2020-02-15 11:22

import Account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_auto_20200214_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='farmer_phone',
            field=models.CharField(max_length=10, unique=True, validators=[Account.models.validate_phone_number], verbose_name="Farmer's Phone Number"),
        ),
    ]
