# Generated by Django 3.0.3 on 2020-02-17 04:49

import Account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_auto_20200215_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPTokenPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, validators=[Account.models.validate_phone_number], verbose_name='Phone Number')),
                ('token', models.CharField(blank=True, max_length=4, verbose_name='Token')),
                ('purpose', models.CharField(choices=[('vermob', 'Verification Mobile'), ('forpas', 'Forgot Password'), ('indent', 'Identify The Account')], default='ver', max_length=50, verbose_name='Purpose')),
                ('created_on', models.DateTimeField(auto_now=True, verbose_name='Created On')),
                ('change_request', models.BooleanField(default=False, verbose_name='Regenerate Token')),
            ],
            options={
                'verbose_name': 'OTPToken',
                'verbose_name_plural': 'OTPTokens',
                'unique_together': {('phone_number', 'purpose')},
            },
        ),
    ]
