# Generated by Django 3.0.3 on 2020-02-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_otptokenphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptokenphone',
            name='change_request',
            field=models.BooleanField(default=True, verbose_name='Regenerate Token'),
        ),
    ]
