# Generated by Django 3.0.3 on 2020-02-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_auto_20200217_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptokenphone',
            name='token_init',
            field=models.BooleanField(default=False, verbose_name='Token Initialised'),
        ),
    ]
