# Generated by Django 3.0.3 on 2020-02-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_otptokenphone_token_init'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptokenphone',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
    ]
