# Generated by Django 3.0.3 on 2020-02-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_auto_20200217_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptokenphone',
            name='token_used',
            field=models.BooleanField(default=False, verbose_name='Token Used'),
        ),
    ]
