# Generated by Django 3.0.3 on 2020-02-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0013_otptokenphone_token_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptokenphone',
            name='changed_tracker',
            field=models.CharField(default='', max_length=50, verbose_name='Changed Tracker'),
        ),
    ]
