# Generated by Django 3.0.3 on 2020-02-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0014_otptokenphone_changed_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptokenphone',
            name='changed_tracker',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Changed Tracker'),
        ),
    ]
