# Generated by Django 3.0.3 on 2020-02-17 08:32

import Account.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0016_remove_otptokenphone_changed_tracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertApply',
            fields=[
                ('applicant_id', models.UUIDField(default=uuid.uuid4, help_text="Expert Applicant's Unique ID", primary_key=True, serialize=False, unique=True, verbose_name="Expert's ID")),
                ('applicant_full_name', models.CharField(help_text="Applicant's Full Name", max_length=100, verbose_name="Applicant's Fullname")),
                ('applicant_gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], default='male', max_length=20, verbose_name="Applicant's Gender")),
                ('applicant_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=50, verbose_name='Status of the Application')),
                ('applicant_email', models.EmailField(help_text="Applicant's Digital Point Of Contact", max_length=254, unique=True, verbose_name="Applicant's Email")),
                ('applicant_verified_email', models.BooleanField(default=False, verbose_name="Applicant's Email Verified")),
                ('applicant_phone', models.CharField(max_length=10, unique=True, validators=[Account.models.validate_phone_number], verbose_name="Applicant's Phone Number")),
                ('applicant_verified_phone', models.BooleanField(default=False, verbose_name="Applicant's Phone Verified")),
                ('applicant_plot_no', models.CharField(blank=True, default='', help_text="Applicant's Plot No", max_length=50, verbose_name='Plot No')),
                ('applicant_street', models.CharField(help_text="Applicant's Street", max_length=150, verbose_name='Steet')),
                ('applicant_landmark', models.CharField(blank=True, help_text="Applicant's Landmark", max_length=100, null=True, verbose_name='Landmark')),
                ('applicant_place', models.CharField(help_text="Applicant's Palces", max_length=70, verbose_name='Places')),
                ('applicant_city', models.CharField(help_text="Applicant's City", max_length=60, verbose_name='City')),
                ('applicant_state', models.CharField(help_text="Applicant's State", max_length=70, verbose_name='State')),
                ('applicant_country', models.CharField(help_text="Applicant's Counrty", max_length=50, verbose_name='Country')),
                ('applicant_supported_docs', models.FileField(help_text='Applicants Supported Docs In zip Format', upload_to=Account.models.docs_upload_location, verbose_name='Applicant Supported Docs')),
            ],
            options={
                'verbose_name': 'ExpertApply',
                'verbose_name_plural': 'ExpertApplys',
            },
        ),
    ]
