# Generated by Django 3.0.3 on 2020-02-17 11:06

import Account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0018_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='expert_dp',
            field=models.ImageField(default='dp/default.jpg', upload_to=Account.models.expert_dp_upload, verbose_name="Expert's Profile Pic"),
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_full_name', models.CharField(help_text="Expert's Full Name", max_length=100, verbose_name="Other's Fullname")),
                ('other_gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')], default='male', max_length=20, verbose_name="Other's Gender")),
                ('other_email', models.EmailField(help_text="Other's Digital Point Of Contact", max_length=254, unique=True, verbose_name="Other's Email")),
                ('other_verified_email', models.BooleanField(default=False, verbose_name="Other's Email Verified")),
                ('other_phone', models.CharField(max_length=10, unique=True, validators=[Account.models.validate_phone_number], verbose_name="Other's Phone Number")),
                ('other_verified_phone', models.BooleanField(default=False, verbose_name="Other's Phone Verified")),
                ('other_post', models.TextField(verbose_name='Post Or Designation')),
                ('other_user_auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_account', to=settings.AUTH_USER_MODEL, verbose_name="Other's Authentication Account")),
            ],
            options={
                'verbose_name': 'Others',
                'verbose_name_plural': 'Otherss',
            },
        ),
    ]
