# Generated by Django 3.0.3 on 2020-02-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0019_auto_20200217_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='other_address',
            field=models.TextField(default='', verbose_name="Other's Address"),
            preserve_default=False,
        ),
    ]
