# Generated by Django 3.0.3 on 2020-02-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0020_others_other_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otptokenphone',
            name='token_init',
        ),
    ]
