# Generated by Django 3.0.3 on 2020-02-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0021_remove_otptokenphone_token_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptokenphone',
            name='token_update',
            field=models.BooleanField(default=False, verbose_name='Token Update'),
        ),
    ]
