# Generated by Django 3.0.3 on 2020-02-18 17:46

import Account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0022_otptokenphone_token_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=Account.models.document_upload, verbose_name='File Upload')),
                ('linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_account_doc', to='Account.ExpertApply', verbose_name='')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
