# Generated by Django 3.0.3 on 2020-02-18 18:04

import Account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0023_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='other_dp',
            field=models.ImageField(default='', upload_to=Account.models.other_dp_upload, verbose_name="Other's DP"),
            preserve_default=False,
        ),
    ]
