# Generated by Django 3.0.3 on 2020-02-11 14:16

import Help.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VedioTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('vedio', models.FileField(upload_to=Help.models.vedio_content, validators=[Help.models.vedio_type_checker], verbose_name='Vedio Content')),
                ('language', models.CharField(max_length=50, verbose_name='Language Type')),
                ('text_content', models.TextField(help_text='This will hold the texual content of the vedio and realated information', verbose_name='Textual Content')),
            ],
            options={
                'verbose_name': 'Vedio Tutorial',
                'verbose_name_plural': 'Vedio Tutorials',
            },
        ),
    ]
