# Generated by Django 3.0.3 on 2020-02-20 09:51

import Community.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, help_text="Comment's Unique ID", primary_key=True, serialize=False, unique=True, verbose_name='Comment ID')),
                ('description', models.TextField(help_text='Description of the comment', verbose_name='Description')),
                ('tags', models.TextField(help_text='Comma Separted data', verbose_name='Tags For unique Identification')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='When')),
                ('img_url', models.URLField(blank=True, null=True, verbose_name='Image_url')),
                ('img', models.ImageField(blank=True, null=True, upload_to=Community.models.upload_image_com, verbose_name='Image')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_comment', to='Account.Expert', verbose_name='Expert')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_comment', to='Account.Farmer', verbose_name='Farmer Account')),
                ('other', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_comment', to='Account.Others', verbose_name='Others')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Reply Back')),
                ('img_url', models.URLField(blank=True, null=True, verbose_name='Image_url')),
                ('img', models.ImageField(blank=True, null=True, upload_to=Community.models.upload_image_reply, verbose_name='Image')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment_reply', to='Community.Comment', verbose_name='Reply On Comment')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_reply', to='Account.Expert', verbose_name='Expert')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_reply', to='Account.Farmer', verbose_name='Farmer Account')),
                ('other', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_reply', to='Account.Others', verbose_name='Others')),
            ],
        ),
        migrations.CreateModel(
            name='PostIng',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, help_text="Post's Unique ID", primary_key=True, serialize=False, unique=True, verbose_name='Post ID')),
                ('tags', models.TextField(help_text='Comma Separted data', verbose_name='Tags For unique Identification')),
                ('description', models.TextField(help_text='Information to Pass', verbose_name='Description')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='When')),
                ('img_url', models.URLField(blank=True, null=True, verbose_name='Image_url')),
                ('img', models.ImageField(blank=True, null=True, upload_to=Community.models.upload_image, verbose_name='Image')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_posts', to='Account.Expert', verbose_name='Expert')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_posts', to='Account.Farmer', verbose_name='Farmer Account')),
                ('other', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_posts', to='Account.Others', verbose_name='Others')),
            ],
            options={
                'verbose_name': 'PostIng',
                'verbose_name_plural': 'PostIngs',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='Community.PostIng', verbose_name='Post commented'),
        ),
    ]
