# Generated by Django 3.0.3 on 2020-02-20 11:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 11, 23, 57, 677193, tzinfo=utc), verbose_name='when It was Replied'),
            preserve_default=False,
        ),
    ]
