# Generated by Django 3.0.3 on 2020-02-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0002_reply_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='when It was Replied'),
        ),
    ]
